### ISSUE TITLE
XXE Vulnerablity.

### ISSUE THREAD

**Issue by zahiritpro** [3breadt/dd-plist#51]
Able to launch Billion Laugh attack (https://en.wikipedia.org/wiki/Billion_laughs_attack).
 
However, adding below code in XMLPropertyListParser seems to restrict the vulnerability.
FACTORY.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);

Please review.

**Comment by 3breadt** [comment]
Can you please share an example on how the Billion-laugh attack can be launched against the XMLPropertyListParser? Because I cannot reproduce it.

All recommended factory settings as per [the XXE prevention cheat sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md#jaxp-documentbuilderfactory-saxparserfactory-and-dom4j) are already in place.
See #26.

A quick unit test confirmed that the current settings prevent the attack. The following exception is thrown by the parser:
`[Fatal Error] :1:1: JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK`

So what is the added benefit of `XMLConstants.FEATURE_SECURE_PROCESSING`?

**Comment by zahiritpro** [comment]
Can you try parsing with the xml content in https://en.wikipedia.org/wiki/Billion_laughs_attack#Code_example

**Comment by 3breadt** [comment]
That's exactly the XML I used for testing.

**Comment by 3breadt** [comment]
If you don't object, I would close this issue.

**Comment by zahiritpro** [comment]
Yeah I see the test working fine.
I could notice if fSecureProcess property of DocumentBuilderFactory is true, the parser works fine.
This property wasn't true when I tried in my application, hence the attack was through.
Will check what is different 

You shall close the issue. Thank you..!
