### ISSUE TITLE
Missing support for GNUstep base64 NSData

### ISSUE THREAD

**Issue by Artoria2e5** [3breadt/dd-plist#57]
Modern GNUstep plists have a more efficient data encoding, and it is the `<[ base64data ]>` format:

GNUstep source that emits the format:
https://github.com/gnustep/libs-base/blob/753c907938c2a8c4d00cf0fbe01b7e0d020f0064/Source/NSPropertyList.m#L1951-L1956 (gnustep/libs-base@9aa5d4cd0403c2d990262c15884181da5d1e32ae)

GNUstep source that parses the format:
https://github.com/gnustep/libs-base/blob/753c907938c2a8c4d00cf0fbe01b7e0d020f0064/Source/NSPropertyList.m#L1202-L1277
(gnustep/libs-base@3f2fa9ddfe507b68fd92843c345c7994b1c1adc8)

(I wish there is a newer documentation page for the GNUstep format, but I have been unable to locate it.)

**Comment by 3breadt** [comment]
I have added support for parsing this newer format, because it apparently is the currently implemented behavior. But this is not documented on the official [GNUStep documentation page](https://gnustep.github.io/resources/documentation/Developer/Base/Reference/NSPropertyList.html). So when writing ASCII property lists, the documented hexadecimal format is used, as before.
